#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# triggering Bitrise build with Bitrise API
echo -e "\n\033[42mGit hook based automation is started\033[0m\n"
set -o errexit
swiftlint Sources --quiet --reporter html > Scripts/swiftlint_report.html
echo -e "\n\033[42mGit hook based automation is completed\033[0m\n"
exit 0


# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
